# -*- coding: utf-8 -*-
"""room.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWGtNn2-c_er2geX1Sf3T6y8kMROhWGu
"""

rooms = {
    101: None, 102: None, 103: None, 104: None, 105: None,
    106: None, 107: None, 108: None, 109: None, 110: None
}
occupied = set()
n = int(input("Enter number of students: "))
for i in range(n):
    name = input("Enter student name: ")
    allotted = False
    for room in rooms:
        if rooms[room] is None:
            rooms[room] = name
            occupied.add(room)
            print(name, "got room", room)
            allotted = True
            break
    if not allotted:
        print("Rooms are full")
        break
print("\nFinal Allotment:")
for room, student in rooms.items():
    print(room, "-", student)
print("Occupied rooms:", occupied)